--CREATE TABLE [dbo].[Accounts] (
--    [Debtor]              VARCHAR (200)  NULL,
--    [AccountName]         VARCHAR (200)  NOT NULL,
--    [MinimumPayment]      MONEY          NULL,
--    [AutomaticallyPaying] MONEY          NULL,
--    [Balance]             MONEY          NULL,
--    [LoanOriginDate]      DATETIME       NULL,
--    [FirstPaymentDate]    DATETIME       NULL,
--    [LastPaymentDate]     DATETIME       NULL,
--    [CreditLimit]         MONEY          NULL,
--    [AvailableCredit]     MONEY          NULL,
--    [InterestRate]        DECIMAL (5, 2) NULL,
--    [AccountNumber]       VARCHAR (200)  NULL
--);

